name: OCR and Generate Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # 每天午夜 UTC 运行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许写入内容（用于提交 changes）

    steps:
    # 1. 检出代码
    - uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # ----- paddleocr 安装步骤 -----
    # 3. 安装 PaddlePaddle (CPU 版本，如需 GPU 请调整)
    #    注意：这里直接指定了 GPU 版本，如果你的 runner 没有 GPU，需要改为 CPU 版本
    #    https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-quickstart.html
    #    CPU 版本安装命令示例：python -m pip install paddlepaddle==3.0.0 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
    - name: Install PaddlePaddle
      run: |
        python -m pip install --upgrade pip
        # 此处使用 CPU 版本，以兼容大多数 runner 环境
        # 如果你的 runner 支持 GPU 且有需求，请参考 PaddlePaddle 官网选择合适的 GPU 版本安装命令
        pip install paddlepaddle==3.0.0 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/

    # 4. 安装 PaddleOCR
    - name: Install PaddleOCR
      run: pip install "paddleocr[all]"

    # 5. 安装其他 Python 依赖 (如果 requirements.txt 中包含 requests, Pillow 等)
    #    注意：移除 Tesseract 相关依赖，因为我们不再使用它
    - name: Install other Python dependencies
      run: |
        # 确保 requirements.txt 不包含 tesseract 相关包
        pip install -r requirements.txt

    # 6. 运行 OCR 脚本
    #    该脚本应已更新为使用 paddleocr
    - name: Run OCR script
      env:
        TZ: Asia/Shanghai # 设置时区，可选
      run: |
        python ocr.py # 假设你的主脚本名为 ocr.py

    # 7. 提交并推送 getsid.bat 文件 (如果发生更改)
    - name: Commit and push getsid.bat
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # 添加 changes to getsid.bat if it exists and has been modified
        # Use `git status --porcelain` to check for changes more robustly
        if [[ $(git status --porcelain | grep "getsid.bat") ]]; then
          echo "Changes detected in getsid.bat, committing..."
          git add getsid.bat
          git commit -m "Automate update of getsid.bat using PaddleOCR"
        else
          echo "No changes to commit for getsid.bat."
        fi
        git push || echo "Nothing to push."

